# This is a basic workflow to help you get started with Actions

name: Weekly update register

# Controls when the workflow will run
on:
  schedule:
    -  cron: '0 16 * * 3'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  aporeg:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2

      - name: Run script
        run: Rscript download-and-write.R

      - name: Commit files
        run: |
          git config --local user.name github-actions
          git config --local user.email "actions@github.com"
          git add data/*
          git add plots/*
          git commit -am "GH ACTION Autorun ${date}"
          git push
        env:
          REPO_KEY: ${{secrets.GITHUB-TOKEN}}
          username: github-actions
